apiVersion: apps/v1
kind: Deployment
metadata:
  name: devpulse-api
  labels:
    app: devpulse-api

spec:
  replicas: 2
  selector:
    matchLabels:
      app: devpulse-api

  template:
    metadata:
      labels:
        app: devpulse-api
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: api
          image: ghcr.io/rakesh9759/devpulse-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: devpulse-redis
            - name: WAREHOUSE_URL
              valueFrom:
                secretKeyRef:
                  name: devpulse-warehouse
                  key: url
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devpulse-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devpulse-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70